import Container from '../../components/Container/Container';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Inter } from 'next/font/google';

import Head from 'next/head';
//import './globals.css';
import { styles } from "./../../styles/container.css";



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='fr'>
      <body>
        <Container>
          <div className={inter.className}>{children}</div>
        </Container>
      </body>
    </html>
  )
}

